### ISSUE TITLE
[Enhancement]: Return library error on `slurm_ops` instead of propagating `CalledProcessError`

### ISSUE THREAD

**Issue by jedel1043** [charmed-hpc/hpc-libs#11]
Should be a pretty nice enhancement, considering that returning `CalledProcessError` is a bit more opaque to the user in contrast to having a nifty `SlurmOpsError` that is visible from the module exports.

**Comment by NucciTheBoss** [comment]
I had the same idea yesterday! Great minds think alike :exploding_head:
