### ISSUE TITLE
[Bug]: Incorrect service name for Slurm prometheus exporter

### ISSUE THREAD

**Issue by NucciTheBoss** [charmed-hpc/hpc-libs#25]
The current name we have for the Slurm Prometheus exporter in `slurm_ops` goes against Debian's convention for Prometheus exporters - `slurm-prometheus-exporter` rather than the standard `prometheus-slurm-exporter` - and the service name provided by our Debian package is `prometheus-slurm-exporter`

Quick fix. We just need to update the `ServiceType` enum to use the correct service name.

**Comment by jedel1043** [comment]
We'll probably want to also open an issue on the slurm-snap, since the service's name is also wrong there.
