### ISSUE TITLE
[Enhancement]: openfiles not configured for hpc use case  

### ISSUE THREAD

**Issue by jamesbeedy** [charmed-hpc/hpc-libs#41]
Ulimit settings of the operating system (`/etc/security/limits.conf`) and for processes `slurmd` and `slurmctld` restrict `slurmscriptd` processes' openfiles to 1048.

```bash
$ srun -pslurmd --pty  bash
ubuntu@juju-1cc933-0:~$ ulimit -n
1048
```

**Comment by NucciTheBoss** [comment]
Default ulimit config on Ubuntu doesn't play nice with HPC use cases. We were originally applying the override in the slurmd operator directly, but it makes sense to just perform the service override here.
